name: BMS Application

on: push

jobs:
  test_env:
    environment: TEST_SECRET
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
        
    - name: Test env vars for python
      run: python -c 'import os;print(os.environ)'
      env:
        ADMIN_PASS: ${{ secrets.ADMIN_PASS }} 
        ADMIN_USER: ${{ secrets.ADMIN_USER }} 
        APP_KEY: ${{ secrets.APP_KEY }} 
        DBMS_PASS: ${{ secrets.DBMS_PASS }} 
        DBMS_USER: ${{ secrets.DBMS_USER }} 
